# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for TestProject

  pod 'ReactiveCocoa', '2.5'
  pod 'BeeHive', '~> 1.6.0'
  pod 'MJExtension', '~> 3.0.13'

end
